[package]
name = "simple-ai-macros"
version = { workspace = true }
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1" }
syn = { version = "2.0", features = ["full", "printing", "parsing"] }
quote = { version = "1.0" }
change-case = { version = "0.2.0" }
