[package]
name = "SimpleNodeEditor"
version = "0.1.0"
description = "Node editor for ai applications."
authors = ["raspirat", "sert"]
license = ""
repository = ""
default-run = "SNE"
edition = "2021"
rust-version = "1.60"

[[bin]]
name = "SNE"
path = "frontend/rust/main.rs"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.4", features = [] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
