[package]
name = "SimpleNodeEditor"
version = "0.1.0"
description = "Node editor for ai applications."
authors = ["raspirat", "sert"]
license = ""
repository = ""
default-run = "SNE"
edition = "2021"
rust-version = "1.60"

[[bin]]
name = "SNE"
path = "bin/src/rust/sne.rs"

[dependencies]
LibFrontSimpleNodeEditor = { path = "lib/frontend"}