[package]
name = "sai_macros"
edition = "2021"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = { version = "1" }
syn = { version = "2.0", features = ["full"] }
quote = { version = "1.0" }
