name = "complex_bundled_node"
description = "A complex bundled node"
author = "Author"
date = "2025-03-10T07:02:17.197379962Z"

[[versions]]
version = "0.0.1"

[[versions.env.deps]]
name = "serde"
versions = ["1.0"]
lib = true
