name = "complex_bundled_node"
description = "A complex bundled node"
author = "Author"
date = "2025-03-10T12:33:26.326848257Z"

[[versions]]
version = "0.0.1"

[[versions.env.deps]]
name = "serde"
versions = ["1.0"]
lib = true

[[versions]]
version = "0.0.2"

[[versions.env.deps]]
name = "serde"
versions = ["1.0"]
lib = true

[[versions.env.deps]]
name = "torch"
versions = ["2.0"]
lib = true
