name = "complex_bundled_node"
description = "A complex bundled node"
author = "Author"
date = "2025-03-03T06:50:31.493551695Z"

[[versions]]
version = "0.0.1"

[[versions.env.deps]]
name = "serde"
versions = ["1.0"]
lib = true
