name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system packages
      run: sudo apt-get install libglib2.0-dev libgtk-3-dev libsoup-3.0
    - name: Build
      run: cargo build --release --features "desktop"
    - name: Run tests
      run: cargo test --verbose
